BitcoreNode:
  network: livenet
  NetworkMonitor:
    host: localhost
    port: 8333
Reporter: none # none, simple, matrix
BitcoreHTTP:
  host: localhost
  port: 8080
LevelUp: ./db
RPC:
  user: user
  pass: password
  protocol: http
  host: 127.0.0.1
  port: 8332
